version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=admin
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data